<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\TaskMaster;
use App\Models\TaskPack;
use App\Models\TaskPackItem;

class OfficialDataSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        TaskPackItem::truncate();
        TaskPack::truncate();
        TaskMaster::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $taskData = [
            // HTML/CSS
            ['category' => 'HTML/CSS', 'order' => 1, 'level' => 1, 'title' => 'Webの仕組みを理解する', 'description' => "【課題内容】\nブラウザがWebページを表示するまでの仕組みをまとめたドキュメントを作成する。\n\n【要件】\n・URLを入力してからページが表示されるまでの流れ（DNS・HTTP・レンダリング）を説明すること\n・フロントエンドとバックエンドの役割の違いを説明すること\n・HTTPとHTTPSの違いを説明すること\n・図やリストを使って視覚的にわかりやすくまとめること\n\n【提出物】\n・まとめたドキュメント（Markdown・Notion・Googleドキュメントなど形式は自由）のURL"],
            ['category' => 'HTML/CSS', 'order' => 2, 'level' => 1, 'title' => 'HTMLで自己紹介ページを作る', 'description' => "【課題内容】\nHTMLのみを使って自己紹介ページを作成し、GitHubにpushする。\n\n【要件】\n・見出し（h1〜h3）・段落（p）・リスト（ul/ol）・リンク（a）・画像（img）を最低1つずつ使うこと\n・名前・趣味・自己PR・目標のいずれかを含めること\n・ファイル名はindex.htmlにすること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'HTML/CSS', 'order' => 3, 'level' => 1, 'title' => 'CSSでページをデザインする', 'description' => "【課題内容】\n前の課題で作成した自己紹介ページにCSSを適用し、デザインを整える。\n\n【要件】\n・外部CSSファイル（style.css）を使うこと（インラインCSSは不可）\n・背景色・文字色・フォントを変更すること\n・ボックスモデル（margin・padding・border）を活用すること\n・リンクのホバースタイルを設定すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'HTML/CSS', 'order' => 4, 'level' => 2, 'title' => 'Flexboxでナビゲーションバーを作る', 'description' => "【課題内容】\nFlexboxを使ってレスポンシブ対応のナビゲーションバーを実装する。\n\n【要件】\n・ロゴ（左）とメニューリスト（右）がFlexboxで横並びになっていること\n・メニュー項目は最低4つ以上あること\n・ホバー時にスタイルが変化すること\n・スマートフォン幅（600px以下）では縦並びに切り替わること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL（GitHub PagesまたはVercel等）"],
            ['category' => 'HTML/CSS', 'order' => 5, 'level' => 2, 'title' => 'CSS Gridでポートフォリオギャラリーを作る', 'description' => "【課題内容】\nCSS Gridを使い、カード型のポートフォリオギャラリーを実装する。\n\n【要件】\n・3列以上のグリッドレイアウトを実装すること\n・各カードに画像・タイトル・説明テキストを含めること\n・カードのホバー時にシャドウや拡大などのエフェクトを実装すること\n・スマートフォン幅（600px以下）では1列表示に切り替わること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'HTML/CSS', 'order' => 6, 'level' => 3, 'title' => 'SCSSでデザインシステムを作る', 'description' => "【課題内容】\nSCSSを使い、再利用可能なデザインシステムを構築する。\n\n【要件】\n・カラー・フォントサイズ・余白をSCSS変数で定義すること\n・ネストを活用してコンポーネントのスタイルを整理すること\n・ミックスインを最低1つ作成すること（例：メディアクエリ用）\n・ボタン・カード・フォームなど最低3種類のUIコンポーネントを作成すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'HTML/CSS', 'order' => 7, 'level' => 4, 'title' => 'アニメーションを実装する', 'description' => "【課題内容】\nCSSアニメーションを使い、Webページに動きを加える。\n\n【要件】\n・@keyframesを使ったアニメーションを最低2種類実装すること（例：フェードイン・スピナー）\n・transitionを使ったホバーエフェクトを最低1種類実装すること\n・animation-delay・animation-durationを活用すること\n・ページロード時のフェードインアニメーションを実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'HTML/CSS', 'order' => 8, 'level' => 4, 'title' => 'デザインカンプをコーディングする', 'description' => "【課題内容】\nFigmaで提供されたデザインカンプを忠実にHTML/CSSでコーディングする。\n\n【要件】\n・Figmaのデザインカンプ（講師から提供またはFigma Communityから取得）を再現すること\n・余白・フォントサイズ・色をデザインカンプに合わせること\n・レスポンシブ対応（スマートフォン・タブレット・PC）を実装すること\n・PixelPerfectを意識し、デザインとの乖離が最小になるようにすること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・Figmaデザインとの比較スクリーンショット"],
            ['category' => 'HTML/CSS', 'order' => 9, 'level' => 5, 'title' => 'SEO・アクセシビリティ対応をする', 'description' => "【課題内容】\n既存のWebページにSEOとアクセシビリティ対応を施す。\n\n【要件】\n・title・description・OGPメタタグを適切に設定すること\n・見出し構造（h1〜h6）を正しく使うこと\n・画像にalt属性を設定すること\n・WAI-ARIAのaria-label・role属性を最低3箇所に設定すること\n・キーボードのみで全コンテンツにアクセスできること\n・Lighthouseでアクセシビリティスコアが90点以上になること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・LighthouseのスコアのスクリーンショットURL"],

            // JavaScript
            ['category' => 'JavaScript', 'order' => 1, 'level' => 1, 'title' => 'JavaScriptで電卓を作る', 'description' => "【課題内容】\nJavaScriptを使い、ブラウザで動作する電卓アプリを実装する。\n\n【要件】\n・0〜9の数字ボタンと四則演算（+・-・×・÷）ボタンを実装すること\n・計算結果を画面に表示すること\n・リセット（AC）ボタンを実装すること\n・連続計算（例：1+2+3）ができること\n・小数点の入力ができること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'JavaScript', 'order' => 2, 'level' => 2, 'title' => '配列とループでクイズアプリを作る', 'description' => "【課題内容】\nJavaScriptの配列とループを使い、クイズアプリを実装する。\n\n【要件】\n・問題と選択肢を配列で管理すること\n・問題は最低10問用意すること\n・問題をランダムな順番で出題すること\n・選択後に正解・不正解をフィードバックすること\n・全問終了後に得点を表示すること\n・もう一度挑戦できるリスタートボタンを実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'JavaScript', 'order' => 3, 'level' => 2, 'title' => 'LocalStorageでTodoアプリを作る', 'description' => "【課題内容】\nLocalStorageを使ってデータを永続化するTodoアプリを実装する。\n\n【要件】\n・タスクの追加・完了切り替え・削除ができること\n・ページをリロードしてもデータが保持されること（LocalStorage使用）\n・未完了・完了済みのタスクをフィルタリングして表示できること\n・空欄のタスク追加を防ぐバリデーションを実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'JavaScript', 'order' => 4, 'level' => 2, 'title' => 'Fetch APIで天気アプリを作る', 'description' => "【課題内容】\nFetch APIを使って外部天気APIからデータを取得し、天気情報を表示するアプリを実装する。\n\n【要件】\n・OpenWeatherMap APIなどの外部APIを使用すること\n・都市名を入力して天気を検索できること\n・気温・天気の状態・湿度を表示すること\n・ローディング中の表示を実装すること\n・API取得失敗時のエラーメッセージを表示すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'JavaScript', 'order' => 5, 'level' => 2, 'title' => '非同期処理とPromiseを理解する', 'description' => "【課題内容】\n非同期処理の仕組みをまとめたドキュメントを作成し、サンプルコードを実装する。\n\n【要件】\n・同期処理と非同期処理の違いをコード例で説明すること\n・コールバック・Promise・async/awaitの3つの書き方を同じ処理で比較すること\n・Promise.all・Promise.raceの使い方をサンプルで示すこと\n・実際に動くサンプルコードをGitHubにpushすること\n\n【提出物】\n・GitHubリポジトリURL\n・まとめドキュメントのURL"],
            ['category' => 'JavaScript', 'order' => 6, 'level' => 3, 'title' => 'モジュール分割でコードを整理する', 'description' => "【課題内容】\n既存のJavaScriptコードをES Modulesを使いモジュール分割してリファクタリングする。\n\n【要件】\n・import/exportを使いファイルを責務ごとに分割すること（例：api.js・ui.js・utils.js）\n・1ファイルあたりの行数を100行以内に収めること\n・各モジュールの役割をコメントで説明すること\n・リファクタリング前後のファイル構成の比較をREADMEに記載すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'JavaScript', 'order' => 7, 'level' => 4, 'title' => 'パフォーマンス最適化をする', 'description' => "【課題内容】\nWebページのパフォーマンスを計測し、改善を行う。\n\n【要件】\n・Lighthouse・Chrome DevToolsでパフォーマンスを計測し、改善前のスコアを記録すること\n・画像の遅延読み込み（loading=lazy）を実装すること\n・入力イベントにデバウンスを実装すること\n・重い計算処理をメモ化（memoize）して最適化すること\n・改善後のLighthouseスコアが改善前より10点以上向上すること\n\n【提出物】\n・GitHubリポジトリURL\n・改善前後のLighthouseスコアのスクリーンショット"],
            ['category' => 'JavaScript', 'order' => 8, 'level' => 5, 'title' => 'PWAを実装する', 'description' => "【課題内容】\n既存のWebアプリにPWA対応を追加し、オフライン動作・インストールができるようにする。\n\n【要件】\n・Web App Manifest（manifest.json）を作成し、アプリ名・アイコン・テーマカラーを設定すること\n・Service Workerを登録し、キャッシュ戦略を実装すること\n・オフライン時にキャッシュから表示できること\n・PCおよびスマートフォンでホーム画面に追加できること\n・LighthouseのPWAスコアが90点以上になること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・LighthouseのPWAスコアのスクリーンショット"],

            // React
            ['category' => 'React', 'order' => 1, 'level' => 2, 'title' => 'Reactでカウンターアプリを作る', 'description' => "【課題内容】\nReactのuseStateを使い、カウンターアプリを実装する。\n\n【要件】\n・カウントを増加・減少・リセットするボタンを実装すること\n・カウントが0未満にならないようにすること\n・カウントの値に応じて色が変わるようにすること（例：0=グレー、正=青、など）\n・コンポーネントを適切に分割すること（例：CounterDisplay・CounterButton）\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'React', 'order' => 2, 'level' => 2, 'title' => 'useEffectでデータ取得アプリを作る', 'description' => "【課題内容】\nuseEffectを使い、外部APIからデータを取得して一覧表示するアプリを実装する。\n\n【要件】\n・useEffectでコンポーネントマウント時にAPIを呼び出すこと\n・JSONPlaceholder等の公開APIからデータを取得すること\n・ローディング中・エラー時・データ表示の3状態を実装すること\n・取得したデータをカード形式で一覧表示すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'React', 'order' => 3, 'level' => 3, 'title' => 'React Routerでマルチページアプリを作る', 'description' => "【課題内容】\nReact Routerを使い、複数ページを持つSPAを実装する。\n\n【要件】\n・最低3ページ（例：ホーム・一覧・詳細）を実装すること\n・URLパラメータ（/posts/:id）を使った詳細ページを実装すること\n・存在しないURLにアクセスした場合の404ページを実装すること\n・共通ナビゲーションコンポーネントを作成すること\n・ナビゲーションのアクティブ状態を実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'React', 'order' => 4, 'level' => 3, 'title' => 'フォームバリデーションを実装する', 'description' => "【課題内容】\nReactの制御コンポーネントを使い、バリデーション付きの会員登録フォームを実装する。\n\n【要件】\n・名前・メールアドレス・パスワード・パスワード確認の入力欄を実装すること\n・各フィールドのバリデーションルールを設定すること（必須・形式・文字数など）\n・入力欄からフォーカスが外れた時点でエラーメッセージを表示すること\n・全項目が有効な場合のみ送信ボタンを活性化すること\n・送信成功時にサンクスメッセージを表示すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'React', 'order' => 5, 'level' => 3, 'title' => 'Context APIでグローバル状態管理をする', 'description' => "【課題内容】\nContext APIを使い、複数コンポーネント間でグローバル状態を共有するアプリを実装する。\n\n【要件】\n・認証状態（ログイン中のユーザー情報）をContextで管理すること\n・ダークモード切り替えをContextで管理すること\n・PropsのバケツリレーなしにContextから値を取得すること\n・カスタムフック（例：useAuth・useTheme）でContextをラップすること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'React', 'order' => 6, 'level' => 3, 'title' => 'axiosでLaravel APIに接続する', 'description' => "【課題内容】\naxiosを使いLaravel APIと通信するReactアプリを実装する。\n\n【要件】\n・axiosのインスタンスを作成しbaseURLとデフォルトヘッダーを設定すること\n・ログイン・ログアウト・ユーザー取得APIと通信すること\n・認証が必要なAPIへのリクエストにトークンまたはCookieを付与すること\n・APIエラー時のエラーハンドリングを実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'React', 'order' => 7, 'level' => 4, 'title' => 'カスタムフックでロジックを分離する', 'description' => "【課題内容】\nカスタムフックを作成し、コンポーネントからロジックを分離する。\n\n【要件】\n・データ取得ロジックをuseFetch（またはuseXxx）カスタムフックに切り出すこと\n・フォームの入力値管理をuseFormカスタムフックに切り出すこと\n・各カスタムフックはローディング状態・エラー状態を返すこと\n・カスタムフックのみを変更してもコンポーネントのUIが壊れないこと\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'React', 'order' => 8, 'level' => 4, 'title' => 'ReactでドラッグandドロップUIを作る', 'description' => "【課題内容】\nドラッグ&ドロップで順番を並び替えられるリストUIを実装する。\n\n【要件】\n・@dnd-kit/coreなどのライブラリを使いドラッグ&ドロップを実装すること\n・並び替え後の順番をstateに反映すること\n・ドラッグ中のアイテムにビジュアルフィードバックを実装すること\n・タッチデバイスでも動作すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'React', 'order' => 9, 'level' => 4, 'title' => 'テストコードを書く', 'description' => "【課題内容】\nReact Testing LibraryとVitestを使い、コンポーネントの単体テストを書く。\n\n【要件】\n・最低3つのコンポーネントにテストを書くこと\n・テキストの表示・ボタンクリック・フォーム入力のテストを含めること\n・モックを使いAPIリクエストのテストを実装すること\n・npm run testでテストが全て通ること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'React', 'order' => 10, 'level' => 5, 'title' => 'コードレビューを受ける', 'description' => "【課題内容】\nこれまで作成したReactアプリのコードレビューを受け、フィードバックをもとに改善する。\n\n【要件】\n・GitHubのプルリクエストを使いコードレビューを依頼すること\n・コードの可読性・パフォーマンス・設計に関するフィードバックを受けること\n・受けたフィードバックをもとにコードを修正してプルリクエストを更新すること\n・フィードバックへの対応内容をコメントに記載すること\n\n【提出物】\n・GitHubプルリクエストURL"],
            ['category' => 'React', 'order' => 11, 'level' => 5, 'title' => '卒業制作：ポートフォリオサイトを公開する', 'description' => "【課題内容】\nReactを使ったポートフォリオサイトを作成し、本番環境にデプロイして公開する。\n\n【要件】\n・自己紹介・スキル・制作物・連絡先のセクションを実装すること\n・制作物は最低3件以上掲載し、各制作物にGitHubリンクを含めること\n・レスポンシブ対応（スマートフォン・PC）を実装すること\n・Vercel・Netlifyなどに本番デプロイすること\n・カスタムドメインまたはサブドメインでアクセスできること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],

            // TypeScript
            ['category' => 'TypeScript', 'order' => 1, 'level' => 2, 'title' => 'TypeScriptの基礎を理解する（型・インターフェース）', 'description' => "【課題内容】\nTypeScriptの基本的な型とインターフェースを使ったサンプルコードを作成する。\n\n【要件】\n・string・number・boolean・配列・タプル・any・unknownの型を使ったコードを書くこと\n・interfaceを使ってUser・Productなど最低2つのオブジェクト型を定義すること\n・typeエイリアスも使い、interfaceとの違いをコメントで説明すること\n・型エラーが発生するコードを意図的に書き、エラー内容をコメントで説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'TypeScript', 'order' => 2, 'level' => 2, 'title' => '関数と型注釈を使う', 'description' => "【課題内容】\n関数の引数・戻り値に型注釈をつけたサンプルコードを作成する。\n\n【要件】\n・通常関数・アロー関数の両方に型注釈をつけること\n・オプショナルパラメータ・デフォルト値を使った関数を実装すること\n・戻り値の型を明示した関数を最低5つ実装すること\n・void・never型を使った関数を含めること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'TypeScript', 'order' => 3, 'level' => 3, 'title' => 'ジェネリクスを理解する', 'description' => "【課題内容】\nジェネリクスを使い、型安全で再利用可能な関数・クラスを実装する。\n\n【要件】\n・ジェネリクスを使った汎用的なデータ取得関数を実装すること\n・ジェネリクスを使ったスタック・キューのいずれかのデータ構造を実装すること\n・型制約（extends）を使ったジェネリクスを実装すること\n・実装した関数・クラスの使用例をコメントで示すこと\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'TypeScript', 'order' => 4, 'level' => 3, 'title' => 'Reactコンポーネントを型付けする', 'description' => "【課題内容】\nReactコンポーネントのpropsとstateにTypeScriptの型をつける。\n\n【要件】\n・React.FC型またはpropsの型定義を使ってコンポーネントを型付けすること\n・必須props・オプショナルprops・デフォルト値を含むコンポーネントを実装すること\n・useStateの型パラメータを明示すること\n・イベントハンドラ（onChange・onClick）の型を適切に設定すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'TypeScript', 'order' => 5, 'level' => 3, 'title' => 'APIレスポンスを型定義する', 'description' => "【課題内容】\nAPIレスポンスの型定義を行い、型安全なAPI通信を実装する。\n\n【要件】\n・APIレスポンスのデータ構造をinterfaceまたはtypeで定義すること\n・axiosまたはfetchのレスポンスにジェネリクスで型をつけること\n・エラーレスポンスの型も定義すること\n・型定義ファイル（.d.tsまたはtypes.ts）を分離して管理すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'TypeScript', 'order' => 6, 'level' => 4, 'title' => 'ユーティリティ型を使う', 'description' => "【課題内容】\nTypeScriptのユーティリティ型を使い、柔軟な型定義を実装する。\n\n【要件】\n・Partial・Required・Readonly・Pickをそれぞれ使った型定義を実装すること\n・OmitとPickを組み合わせてAPIリクエスト用の型を定義すること\n・Recordを使ったオブジェクト型を実装すること\n・各ユーティリティ型の使い方と使いどころをコメントで説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'TypeScript', 'order' => 7, 'level' => 4, 'title' => '既存JSプロジェクトをTSに移行する', 'description' => "【課題内容】\n既存のJavaScriptプロジェクトにTypeScriptを導入し、段階的に型付けを行う。\n\n【要件】\n・tsconfig.jsonを適切に設定すること\n・.jsファイルを.tsxまたは.tsに変換すること\n・anyを使わず明示的な型定義を行うこと\n・移行の手順とポイントをREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・移行手順のREADME"],

            // PHP
            ['category' => 'PHP', 'order' => 1, 'level' => 1, 'title' => 'コマンドラインの基本操作をマスターする', 'description' => "【課題内容】\nターミナルの基本コマンドを習得し、操作記録をドキュメントにまとめる。\n\n【要件】\n・ls・cd・mkdir・rm・cp・mv・touchコマンドを使えること\n・ファイルの内容を表示するcat・less・headコマンドを使えること\n・ファイルの検索（find・grep）を使えること\n・パーミッション（chmod・chown）の基本を理解すること\n・各コマンドの使い方と実行例をまとめたドキュメントを作成すること\n\n【提出物】\n・まとめドキュメントのURL（Notion・GitHubなど形式は自由）"],
            ['category' => 'PHP', 'order' => 2, 'level' => 1, 'title' => 'PHPの基礎文法を習得する', 'description' => "【課題内容】\nPHPの基礎文法を使い、簡単なコンソールプログラムを作成する。\n\n【要件】\n・変数・定数・型（string・int・float・bool・array）を使うこと\n・条件分岐（if/elseif/else・switch）を実装すること\n・ループ（for・foreach・while）を実装すること\n・関数を最低3つ定義して使うこと\n・配列の操作（追加・削除・検索・ソート）を実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'PHP', 'order' => 3, 'level' => 1, 'title' => 'PHPでオブジェクト指向を理解する', 'description' => "【課題内容】\nPHPのオブジェクト指向の概念を使い、簡単なクラス設計を実装する。\n\n【要件】\n・クラスを最低2つ定義し、プロパティとメソッドを実装すること\n・コンストラクタ（__construct）を実装すること\n・継承（extends）を使い、親クラスのメソッドをオーバーライドすること\n・アクセス修飾子（public・protected・private）を適切に使うこと\n・インターフェース（interface）を1つ定義して実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'PHP', 'order' => 4, 'level' => 2, 'title' => 'MySQLの基本操作をマスターする', 'description' => "【課題内容】\nMySQLでデータベースとテーブルを作成し、基本的なSQL操作を習得する。\n\n【要件】\n・データベースとテーブルを作成するSQL（CREATE）を書くこと\n・テストデータを挿入するSQL（INSERT）を書くこと\n・条件付き検索・ソート・LIMIT付きのSELECTを書くこと\n・UPDATE・DELETEを書くこと\n・実行したSQLをまとめたドキュメントを作成すること\n\n【提出物】\n・GitHubリポジトリURL（SQLファイル含む）\n・まとめドキュメントのURL"],
            ['category' => 'PHP', 'order' => 5, 'level' => 2, 'title' => 'PHPとMySQLを連携させる', 'description' => "【課題内容】\nPDOを使いPHPからMySQLに接続し、データを管理するWebアプリを実装する。\n\n【要件】\n・PDOを使いMySQLに接続すること\n・フォームから入力したデータをDBに保存できること\n・DBから取得したデータを一覧表示できること\n・プリペアドステートメントを使いSQLインジェクション対策を行うこと\n・エラーハンドリングを実装すること\n\n【提出物】\n・GitHubリポジトリURL"],

            // Laravel
            ['category' => 'Laravel', 'order' => 1, 'level' => 2, 'title' => 'LaravelとDockerで開発環境を構築する', 'description' => "【課題内容】\nLaravel SailとDockerを使い、ローカル開発環境を構築する。\n\n【要件】\n・Laravel Sailを使い、Docker上でLaravelが起動すること\n・MySQLコンテナが起動しLaravelと接続できること\n・php artisan migrateが成功すること\n・php artisan tinkerでDBにアクセスできること\n・環境構築手順をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・環境構築手順のREADME"],
            ['category' => 'Laravel', 'order' => 2, 'level' => 2, 'title' => 'MVC構造とルーティングを理解する', 'description' => "【課題内容】\nLaravelのMVC構造を理解し、シンプルなページ表示アプリを実装する。\n\n【要件】\n・routes/web.phpにルートを定義すること\n・コントローラを作成しビューにデータを渡すこと\n・Bladeテンプレートを使いHTMLを表示すること\n・RESTfulなルーティング（resource）を最低1つ定義すること\n・ルーティングの一覧（php artisan route:list）をREADMEに記載すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 3, 'level' => 2, 'title' => 'MigrationとEloquentでDB操作をする', 'description' => "【課題内容】\nMigrationでテーブルを作成し、EloquentモデルでCRUDを実装する。\n\n【要件】\n・Migrationでテーブルを最低2つ作成すること\n・Eloquentモデルを使いCRUD（作成・取得・更新・削除）を実装すること\n・Seederを使いテストデータを投入すること\n・Laravelのクエリビルダを使ったクエリを最低3種類実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 4, 'level' => 2, 'title' => 'リレーションとeager loadingを使う', 'description' => "【課題内容】\nEloquentのリレーションを定義し、N+1問題をeager loadingで解決する。\n\n【要件】\n・hasMany・belongsToのリレーションを実装すること\n・N+1問題が発生するコードと、with()で解決したコードを両方書いてクエリ数の違いを確認すること\n・hasManyThroughまたはbelongsToManyのいずれかも実装すること\n・リレーションを使った絞り込みクエリ（whereHas）を実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 5, 'level' => 2, 'title' => 'バリデーションとエラーレスポンスを実装する', 'description' => "【課題内容】\nFormRequestクラスを使いバリデーションを実装し、エラー内容をJSONで返すAPIを作成する。\n\n【要件】\n・FormRequestクラスを使いバリデーションルールを定義すること\n・必須・最大文字数・メール形式・一意性など最低5種類のルールを使うこと\n・バリデーションエラー時に422ステータスコードとエラー内容をJSONで返すこと\n・日本語のエラーメッセージを設定すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 6, 'level' => 2, 'title' => 'Sanctumで認証APIを実装する', 'description' => "【課題内容】\nLaravel Sanctumを使いセッション認証のAPI（ログイン・ログアウト・ユーザー取得）を実装する。\n\n【要件】\n・/auth/login・/auth/logout・/api/userの3エンドポイントを実装すること\n・未認証のリクエストに401を返すこと\n・CSRF保護を設定すること\n・フロントエンド（ReactまたはVue）からログインして認証状態を保持できること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 7, 'level' => 2, 'title' => 'APIリソースでレスポンスを整形する', 'description' => "【課題内容】\nAPI Resourceクラスを使い、レスポンスのデータ構造を統一する。\n\n【要件】\n・ResourceクラスとResourceCollectionクラスを作成すること\n・不要なフィールドを除外し、必要なフィールドのみをレスポンスに含めること\n・リレーション先のデータをネストして返すこと\n・ページネーション付きのCollection Resourceを実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 8, 'level' => 3, 'title' => 'ファイルアップロードを実装する', 'description' => "【課題内容】\nLaravelのストレージ機能を使い、ファイルアップロード機能を実装する。\n\n【要件】\n・画像ファイルのアップロードAPIを実装すること\n・ファイルサイズ・拡張子のバリデーションを実装すること\n・ストレージ（public・s3のいずれか）に保存すること\n・保存したファイルのURLをレスポンスに含めること\n・古いファイルを削除する更新機能を実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 9, 'level' => 3, 'title' => '検索・フィルタ・ソートAPIを作る', 'description' => "【課題内容】\nクエリパラメータを使い、検索・フィルタ・ソートができるAPIを実装する。\n\n【要件】\n・キーワード検索（q=xxx）を実装すること\n・カテゴリなどのフィルタ（category=xxx）を実装すること\n・並び替え（sort=created_at&order=desc）を実装すること\n・ページネーション（page=1&per_page=10）を実装すること\n・各クエリパラメータを組み合わせて使えること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 10, 'level' => 3, 'title' => 'Policyで権限管理を実装する', 'description' => "【課題内容】\nLaravelのPolicyを使い、ロールに応じたアクセス制御を実装する。\n\n【要件】\n・Policyクラスを作成し、viewAny・view・create・update・deleteを定義すること\n・管理者と一般ユーザーで操作権限を分けること\n・他のユーザーのリソースを編集・削除できないよう制御すること\n・権限がない場合に403を返すこと\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 11, 'level' => 3, 'title' => 'キューとジョブで非同期処理をする', 'description' => "【課題内容】\nLaravelのキューとジョブを使い、メール送信を非同期処理として実装する。\n\n【要件】\n・Jobクラスを作成し、メール送信処理を実装すること\n・キューをdatabaseドライバで設定し、jobs・failed_jobsテーブルを作成すること\n・php artisan queue:workでジョブが処理されること\n・ジョブ失敗時のリトライとfailed_jobsへの記録を確認すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 12, 'level' => 3, 'title' => 'イベントとリスナーで疎結合設計をする', 'description' => "【課題内容】\nLaravelのイベントとリスナーを使い、処理を疎結合に設計する。\n\n【要件】\n・Eventクラスを最低1つ作成すること（例：UserRegistered・OrderPlaced）\n・Listenerクラスを作成しイベント発火時の処理を実装すること\n・EventServiceProviderにイベントとリスナーを登録すること\n・イベント発火後にリスナーが実行されることを確認すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 13, 'level' => 3, 'title' => 'キャッシュでAPIを高速化する', 'description' => "【課題内容】\nLaravelのキャッシュ機能を使い、APIのレスポンスを高速化する。\n\n【要件】\n・Cache::remember()を使いDBクエリ結果をキャッシュすること\n・キャッシュの有効期限を適切に設定すること\n・データ更新時にキャッシュを削除・更新すること\n・キャッシュの有無でレスポンスタイムを比較し結果をREADMEに記載すること\n\n【提出物】\n・GitHubリポジトリURL\n・パフォーマンス比較のREADME"],
            ['category' => 'Laravel', 'order' => 14, 'level' => 3, 'title' => 'DBトランザクションで整合性を保つ', 'description' => "【課題内容】\nDBトランザクションを使い、複数のDB操作の整合性を保つ実装を行う。\n\n【要件】\n・DB::transaction()を使い、複数のテーブル更新をひとまとめにすること\n・途中でエラーが発生した場合に全てがロールバックされることを確認すること\n・楽観ロックまたは悲観ロックを実装すること\n・トランザクションが必要な理由をREADMEで説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 15, 'level' => 3, 'title' => 'APIドキュメントを作成する', 'description' => "【課題内容】\n作成したAPIのドキュメントを作成し、共有できる状態にする。\n\n【要件】\n・全エンドポイントのURL・メソッド・リクエスト・レスポンスを記載すること\n・認証が必要なエンドポイントを明示すること\n・エラーレスポンスのパターンを記載すること\n・Swagger（OpenAPI）またはPostman Collectionを作成してエクスポートすること\n\n【提出物】\n・GitHubリポジトリURL\n・APIドキュメントURL（Swagger UIまたはPostman公開リンク）"],
            ['category' => 'Laravel', 'order' => 16, 'level' => 4, 'title' => 'PHPUnitでFeatureテストを書く', 'description' => "【課題内容】\nPHPUnitのFeatureテストを使い、APIエンドポイントの動作を自動テストする。\n\n【要件】\n・最低5つのAPIエンドポイントのFeatureテストを書くこと\n・正常系（200・201）と異常系（401・403・422）のテストを含めること\n・テスト用DBにRefreshDatabaseトレイトを使うこと\n・php artisan testで全テストが通ること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 17, 'level' => 4, 'title' => 'リファクタリングしてコードを改善する', 'description' => "【課題内容】\n既存のコードをリファクタリングし、保守性を高める。\n\n【要件】\n・コントローラから業務ロジックをServiceクラスに移動すること\n・DBアクセスをRepositoryクラスに集約すること\n・重複したコードをメソッドや基底クラスに抽出すること\n・リファクタリング前後のコードをGitのブランチで比較できるようにすること\n・リファクタリングの方針と変更内容をREADMEに記載すること\n\n【提出物】\n・GitHubリポジトリURL\n・リファクタリング内容のREADME"],
            ['category' => 'Laravel', 'order' => 18, 'level' => 4, 'title' => 'セキュリティ対策を実装する', 'description' => "【課題内容】\nLaravelアプリにセキュリティ対策を実装し、脆弱性を防ぐ。\n\n【要件】\n・Eloquentのモデルにfillableを設定しマスアサインメント対策をすること\n・XSSを防ぐためBladeのエスケープ（{{ }}）を使うこと\n・CSRF保護が有効になっていることを確認すること\n・パスワードをbcryptでハッシュ化していることを確認すること\n・セキュリティ対策の内容をまとめたドキュメントを作成すること\n\n【提出物】\n・GitHubリポジトリURL\n・セキュリティ対策ドキュメントのURL"],
            ['category' => 'Laravel', 'order' => 19, 'level' => 4, 'title' => 'パフォーマンスチューニングをする', 'description' => "【課題内容】\nLaravelアプリのパフォーマンスを計測し、改善する。\n\n【要件】\n・Laravel TelescopeまたはクエリログでN+1問題を特定すること\n・eager loadingでN+1問題を解消すること\n・よく使うカラムにインデックスを追加すること\n・改善前後のクエリ数とレスポンスタイムを比較してREADMEに記載すること\n\n【提出物】\n・GitHubリポジトリURL\n・パフォーマンス改善レポートのREADME"],
            ['category' => 'Laravel', 'order' => 20, 'level' => 4, 'title' => 'WebSocketでリアルタイム通信を実装する', 'description' => "【課題内容】\nLaravel BroadcastingとPusherを使い、リアルタイム更新のチャット機能を実装する。\n\n【要件】\n・Pusherアカウントを作成しLaravelとの接続設定を行うこと\n・メッセージ送信時にブロードキャストイベントを発火すること\n・フロントエンド（Laravel Echoまたはsocket.io）でイベントをリッスンしリアルタイムに表示すること\n・チャット画面にメッセージ一覧・入力フォームを実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'Laravel', 'order' => 21, 'level' => 5, 'title' => '外部APIと連携するサービスを作る', 'description' => "【課題内容】\n外部APIと連携した機能をLaravelに実装する。\n\n【要件】\n・SendGrid・Mailgunなどのメール送信API、またはStripeなどの決済APIを1つ選び実装すること\n・APIキーを.envで管理すること\n・APIエラー時の例外処理を実装すること\n・外部APIとの通信をServiceクラスに集約すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 22, 'level' => 5, 'title' => 'マイクロサービスの基礎を理解する', 'description' => "【課題内容】\nマイクロサービスアーキテクチャの概念をまとめたドキュメントを作成する。\n\n【要件】\n・モノリシックとマイクロサービスの違いを説明すること\n・マイクロサービスのメリット・デメリットを説明すること\n・サービス間の通信方法（REST・gRPC・メッセージキュー）を説明すること\n・実際のシステム例（ECサイト等）をマイクロサービスに分割した設計図を作成すること\n\n【提出物】\n・まとめドキュメントのURL（Notion・GitHubなど形式は自由）"],
            ['category' => 'Laravel', 'order' => 23, 'level' => 5, 'title' => 'GraphQL APIを実装する', 'description' => "【課題内容】\nLighthouseを使いLaravelにGraphQL APIを実装する。\n\n【要件】\n・LighthouseをインストールしGraphQLスキーマを定義すること\n・Query（取得）とMutation（作成・更新・削除）を実装すること\n・GraphQL PlaygroundまたはApollo Studioで動作確認できること\n・RESTとGraphQLの違いをREADMEで比較説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Laravel', 'order' => 24, 'level' => 5, 'title' => 'コードレビューを受ける', 'description' => "【課題内容】\nこれまで作成したLaravelアプリのコードレビューを受け、フィードバックをもとに改善する。\n\n【要件】\n・GitHubのプルリクエストを使いコードレビューを依頼すること\n・コードの設計・セキュリティ・パフォーマンスに関するフィードバックを受けること\n・受けたフィードバックをもとにコードを修正してプルリクエストを更新すること\n・フィードバックへの対応内容をコメントに記載すること\n\n【提出物】\n・GitHubプルリクエストURL"],
            ['category' => 'Laravel', 'order' => 25, 'level' => 5, 'title' => '卒業制作：ECサイトバックエンドAPIを作る', 'description' => "【課題内容】\n商品・カート・注文・認証を備えたECサイトのバックエンドAPIをLaravelで実装しデプロイする。\n\n【要件】\n・ユーザー認証（登録・ログイン・ログアウト）APIを実装すること\n・商品一覧・詳細・カテゴリフィルタAPIを実装すること\n・カートの追加・削除・数量変更APIを実装すること\n・注文確定・注文履歴APIを実装すること\n・本番環境にデプロイしAPIドキュメントを作成すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・APIドキュメントURL"],

            // Python
            ['category' => 'Python', 'order' => 1, 'level' => 1, 'title' => 'Python環境構築をする', 'description' => "【課題内容】\nPythonの開発環境を構築し、動作確認ができる状態にする。\n\n【要件】\n・Python 3.10以上をインストールすること\n・仮想環境（venv）を作成し有効化できること\n・pipでライブラリをインストールし、requirements.txtに出力できること\n・Hello Worldをターミナルで実行できること\n・環境構築手順をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・環境構築手順のREADME"],
            ['category' => 'Python', 'order' => 2, 'level' => 1, 'title' => 'Pythonの基礎文法を習得する', 'description' => "【課題内容】\nPythonの基礎文法を使い、コンソールで動作するプログラムを作成する。\n\n【要件】\n・変数・型（str・int・float・bool・list・dict）を使うこと\n・条件分岐（if/elif/else）を実装すること\n・ループ（for・while）とリスト内包表記を使うこと\n・関数を最低3つ定義して使うこと\n・例外処理（try/except）を実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Python', 'order' => 3, 'level' => 1, 'title' => 'リスト・辞書・タプルを使う', 'description' => "【課題内容】\nPythonのリスト・辞書・タプルを使いデータ操作のプログラムを作成する。\n\n【要件】\n・リストのスライス・ソート・検索・内包表記を使うこと\n・辞書のCRUD操作（追加・取得・更新・削除）を実装すること\n・タプルを使ったデータ管理を実装すること\n・リスト・辞書・タプルの使い分けをコメントで説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Python', 'order' => 4, 'level' => 2, 'title' => 'クラスとオブジェクト指向を理解する', 'description' => "【課題内容】\nPythonのクラスを使いオブジェクト指向の概念を実践する。\n\n【要件】\n・クラスを最低2つ定義し、__init__・インスタンスメソッド・クラスメソッド・静的メソッドを実装すること\n・継承を使い、親クラスのメソッドをオーバーライドすること\n・__str__・__repr__マジックメソッドを実装すること\n・カプセル化（プライベート変数）を使うこと\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Python', 'order' => 5, 'level' => 2, 'title' => 'ファイル操作をする', 'description' => "【課題内容】\nPythonでテキストファイル・CSVファイルの読み書きを実装する。\n\n【要件】\n・テキストファイルへの書き込みと読み込みを実装すること\n・CSVファイルをcsvモジュールで読み込み、データを加工して別ファイルに書き出すこと\n・ファイルが存在しない場合のエラーハンドリングを実装すること\n・with文を使いファイルを安全に開閉すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Python', 'order' => 6, 'level' => 2, 'title' => '外部ライブラリを使う（requests等）', 'description' => "【課題内容】\nrequestsライブラリを使い外部APIからデータを取得するプログラムを実装する。\n\n【要件】\n・requestsライブラリをpipでインストールすること\n・公開API（例：GitHub API・OpenWeatherMap API）からGETリクエストでデータを取得すること\n・取得したJSONデータを解析し、必要な情報を抽出して表示すること\n・HTTPエラー（404・500等）をハンドリングすること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Python', 'order' => 7, 'level' => 3, 'title' => 'データ処理をする（pandas入門）', 'description' => "【課題内容】\npandasを使いCSVデータの読み込み・集計・加工・可視化を行う。\n\n【要件】\n・CSVファイルをpandasのDataFrameで読み込むこと\n・欠損値の確認と処理を実装すること\n・グループ集計（groupby）を使い統計情報を出力すること\n・matplotlibまたはseabornでグラフを1つ以上作成すること\n・加工したデータを別のCSVファイルに出力すること\n\n【提出物】\n・GitHubリポジトリURL"],

            // Django
            ['category' => 'Django', 'order' => 1, 'level' => 2, 'title' => 'Djangoで開発環境を構築する', 'description' => "【課題内容】\nDjangoとDockerを使い開発環境を構築する。\n\n【要件】\n・DockerでPython+Django+PostgreSQL（またはMySQL）の環境を構築すること\n・django-admin startprojectでプロジェクトを作成すること\n・python manage.py runserverでサーバーが起動すること\n・python manage.py migrateが成功すること\n・環境構築手順をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・環境構築手順のREADME"],
            ['category' => 'Django', 'order' => 2, 'level' => 2, 'title' => 'MVTパターンを理解する', 'description' => "【課題内容】\nDjangoのMVTパターンを理解し、簡単なWebページを実装する。\n\n【要件】\n・Model・View・Templateの役割の違いをREADMEで説明すること\n・URLルーティングを設定しViewを呼び出すこと\n・Templateでデータを受け取りHTMLを表示すること\n・静的ファイル（CSS）をテンプレートに適用すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Django', 'order' => 3, 'level' => 2, 'title' => 'モデルとマイグレーションを使う', 'description' => "【課題内容】\nDjangoのモデルとMigrationを使いデータベースを管理する。\n\n【要件】\n・Modelクラスを最低2つ定義すること\n・python manage.py makemigrationsとmigrateを実行すること\n・Django管理画面（admin）にモデルを登録しデータを操作できること\n・ForeignKeyによるリレーションを実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Django', 'order' => 4, 'level' => 3, 'title' => 'ビューとテンプレートを作る', 'description' => "【課題内容】\nクラスベースビューとDjangoテンプレートを使いCRUDページを実装する。\n\n【要件】\n・ListView・DetailView・CreateView・UpdateView・DeleteViewを実装すること\n・テンプレートの継承（base.htmlの継承）を使うこと\n・フォームを使いデータの作成・更新ができること\n・削除前に確認画面を表示すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Django', 'order' => 5, 'level' => 3, 'title' => 'Formバリデーションを実装する', 'description' => "【課題内容】\nDjangoFormを使いフォームのバリデーションを実装する。\n\n【要件】\n・ModelFormを使いバリデーションを実装すること\n・カスタムバリデーション（clean_xxx）を最低1つ実装すること\n・エラーメッセージをテンプレートに表示すること\n・フォームのCSRF保護が有効になっていることを確認すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Django', 'order' => 6, 'level' => 3, 'title' => 'Django REST Frameworkを使う', 'description' => "【課題内容】\nDjango REST FrameworkでCRUD APIを実装する。\n\n【要件】\n・Serializerを作成しモデルデータをJSON形式でシリアライズすること\n・ViewSetとRouterを使いCRUD APIを実装すること\n・一覧・詳細・作成・更新・削除の全エンドポイントを実装すること\n・ページネーションを設定すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Django', 'order' => 7, 'level' => 4, 'title' => '認証機能を実装する', 'description' => "【課題内容】\nDjango REST FrameworkにJWT認証を導入し認証APIを実装する。\n\n【要件】\n・djangorestframework-simplejwtを使いJWT認証を設定すること\n・ログイン（トークン取得）・リフレッシュ・ログアウトAPIを実装すること\n・認証が必要なエンドポイントに権限クラスを設定すること\n・未認証リクエストに401を返すこと\n\n【提出物】\n・GitHubリポジトリURL"],

            // Java
            ['category' => 'Java', 'order' => 1, 'level' => 1, 'title' => 'Java環境構築をする', 'description' => "【課題内容】\nJavaの開発環境を構築しHello Worldを実行する。\n\n【要件】\n・JDK 17以上をインストールすること\n・IntelliJ IDEAまたはEclipseをインストールすること\n・Hello Worldをコンパイル・実行できること\n・Mavenまたはgradleでプロジェクトを作成できること\n・環境構築手順をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・環境構築手順のREADME"],
            ['category' => 'Java', 'order' => 2, 'level' => 1, 'title' => 'Javaの基礎文法を習得する', 'description' => "【課題内容】\nJavaの基礎文法を使いコンソールアプリを実装する。\n\n【要件】\n・プリミティブ型（int・double・boolean・char）と参照型を使うこと\n・条件分岐（if/else・switch）を実装すること\n・ループ（for・while・for-each）を実装すること\n・メソッドを最低3つ定義して使うこと\n・配列と基本的な操作を実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Java', 'order' => 3, 'level' => 2, 'title' => 'オブジェクト指向を理解する（クラス・継承）', 'description' => "【課題内容】\nJavaのオブジェクト指向の概念をクラス設計で実践する。\n\n【要件】\n・抽象クラスを定義し、最低2つのサブクラスを実装すること\n・インターフェースを1つ定義して実装すること\n・継承・オーバーライド・ポリモーフィズムを使うこと\n・アクセス修飾子（public・protected・private）を適切に使うこと\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Java', 'order' => 4, 'level' => 2, 'title' => '例外処理を実装する', 'description' => "【課題内容】\nJavaの例外処理を実装し、独自の例外クラスを作成する。\n\n【要件】\n・try-catch-finallyを使い例外処理を実装すること\n・検査例外（IOException等）と非検査例外（RuntimeException等）の違いを理解し使うこと\n・独自の例外クラスを最低1つ作成すること\n・多重catch（マルチキャッチ）を実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Java', 'order' => 5, 'level' => 2, 'title' => 'コレクションを使う', 'description' => "【課題内容】\nJavaのコレクションフレームワークを使いデータ管理を実装する。\n\n【要件】\n・ArrayList・LinkedList・HashMapを使ったデータ操作を実装すること\n・Streamを使いフィルタ・マッピング・集計を実装すること\n・Iteratorを使ったループを実装すること\n・各コレクションの特徴と使い分けをコメントで説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Java', 'order' => 6, 'level' => 3, 'title' => 'ファイルI/Oを実装する', 'description' => "【課題内容】\nJavaでテキストファイルの読み書きを実装する。\n\n【要件】\n・BufferedReader・BufferedWriterを使いテキストファイルを読み書きすること\n・Java NIOのFilesクラスを使ったファイル操作も実装すること\n・ファイルが存在しない・権限がない場合の例外処理を実装すること\n・try-with-resourcesを使いリソースを安全に解放すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Java', 'order' => 7, 'level' => 3, 'title' => 'ユニットテストを書く（JUnit）', 'description' => "【課題内容】\nJUnit 5を使いJavaのメソッドに対するユニットテストを書く。\n\n【要件】\n・最低3つのクラスにJUnitテストを書くこと\n・正常系・異常系・境界値のテストケースを含めること\n・Mockitoを使い依存クラスをモック化すること\n・mvn test（またはgradle test）でテストが全て通ること\n\n【提出物】\n・GitHubリポジトリURL"],

            // Spring Boot
            ['category' => 'Spring Boot', 'order' => 1, 'level' => 2, 'title' => 'Spring Bootで開発環境を構築する', 'description' => "【課題内容】\nSpring Bootの開発環境を構築しHello World APIを実装する。\n\n【要件】\n・Spring Initializrを使いSpring Boot（Web・JPA・MySQL Driver）のプロジェクトを作成すること\n・GET /hello でHello Worldを返すAPIを実装すること\n・application.propertiesでDB接続設定を行うこと\n・環境構築手順をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・環境構築手順のREADME"],
            ['category' => 'Spring Boot', 'order' => 2, 'level' => 2, 'title' => 'REST APIを作る', 'description' => "【課題内容】\nSpring Bootを使いCRUDのREST APIを実装する。\n\n【要件】\n・@RestController・@GetMapping・@PostMapping・@PutMapping・@DeleteMappingを使うこと\n・リクエストボディを@RequestBodyで受け取ること\n・レスポンスに適切なHTTPステータスコードを設定すること\n・@PathVariableと@RequestParamを使ったエンドポイントを実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Spring Boot', 'order' => 3, 'level' => 3, 'title' => 'Spring Data JPAでDB操作をする', 'description' => "【課題内容】\nSpring Data JPAを使いデータベースとのCRUD操作を実装する。\n\n【要件】\n・@Entityアノテーションでエンティティクラスを定義すること\n・JpaRepositoryを継承したRepositoryインターフェースを作成すること\n・カスタムクエリ（@Queryまたはメソッド名クエリ）を最低2つ実装すること\n・@OneToMany・@ManyToOneのリレーションを実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Spring Boot', 'order' => 4, 'level' => 3, 'title' => 'バリデーションを実装する', 'description' => "【課題内容】\nBean Validationを使いリクエストのバリデーションを実装する。\n\n【要件】\n・@NotNull・@NotBlank・@Size・@Email・@Minなどのアノテーションを使うこと\n・@Validアノテーションでバリデーションを有効化すること\n・バリデーションエラー時に400ステータスとエラー内容をJSONで返すこと\n・カスタムバリデーションアノテーションを最低1つ実装すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Spring Boot', 'order' => 5, 'level' => 4, 'title' => 'Spring Securityで認証を実装する', 'description' => "【課題内容】\nSpring SecurityとJWTを使い認証機能を実装する。\n\n【要件】\n・ログイン・ログアウト・ユーザー登録APIを実装すること\n・JWTを発行し認証が必要なAPIにアクセス制御を設定すること\n・パスワードをBCryptでハッシュ化すること\n・未認証リクエストに401、権限不足に403を返すこと\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Spring Boot', 'order' => 6, 'level' => 4, 'title' => 'テストを書く', 'description' => "【課題内容】\nJUnit 5とMockitoを使いSpring BootのControllerとServiceのテストを書く。\n\n【要件】\n・@WebMvcTestを使いControllerのテストを書くこと\n・Mockitoを使いServiceをモック化すること\n・正常系・異常系のテストケースを各エンドポイントに書くこと\n・mvn testでテストが全て通ること\n\n【提出物】\n・GitHubリポジトリURL"],

            // Git/GitHub
            ['category' => 'Git/GitHub', 'order' => 1, 'level' => 1, 'title' => 'Git/GitHubでバージョン管理をする', 'description' => "【課題内容】\nGitとGitHubを使いコードのバージョン管理を習得する。\n\n【要件】\n・git init・add・commit・pushを使いローカルのコードをGitHubにpushすること\n・コミットメッセージは「feat:・fix:・docs:」などのプレフィックスをつけること\n・git logでコミット履歴を確認できること\n・.gitignoreを設定しnode_modules・.envなどを除外すること\n・GitHubのREADMEにプロジェクトの概要を記載すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Git/GitHub', 'order' => 2, 'level' => 2, 'title' => 'Git/GitHubでチーム開発の流れを理解する', 'description' => "【課題内容】\nブランチを使ったチーム開発のワークフローを実践する。\n\n【要件】\n・mainブランチから機能ブランチ（feature/xxx）を切って開発すること\n・GitHubにプルリクエストを作成し、マージすること\n・意図的にコンフリクトを発生させて解消すること\n・GitHub Issueを使いタスク管理を行うこと\n・作業の流れをREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL（ブランチ・プルリクエストの履歴が残っていること）"],
            ['category' => 'Git/GitHub', 'order' => 3, 'level' => 3, 'title' => 'GitHub ActionsでCIパイプラインを作る', 'description' => "【課題内容】\nGitHub Actionsを使いプッシュ時に自動でテストが実行されるCIパイプラインを構築する。\n\n【要件】\n・.github/workflows/ci.ymlを作成すること\n・mainブランチへのpushとプルリクエスト時にCIが実行されること\n・テスト（npm test・php artisan testなど）が自動実行されること\n・テスト失敗時にCIが失敗ステータスになること\n\n【提出物】\n・GitHubリポジトリURL（GitHub ActionsのCI実行ログが確認できること）"],
            ['category' => 'Git/GitHub', 'order' => 4, 'level' => 3, 'title' => 'GitHub ActionsでCDパイプラインを作る', 'description' => "【課題内容】\nGitHub Actionsを使いmainブランチへのマージ時に本番環境へ自動デプロイするCDパイプラインを構築する。\n\n【要件】\n・.github/workflows/cd.ymlを作成すること\n・mainブランチへのpush時にデプロイが自動実行されること\n・GitHub SecretsにAPIキーやサーバー情報を設定すること\n・デプロイ成功・失敗の通知を設定すること\n\n【提出物】\n・GitHubリポジトリURL（GitHub ActionsのCD実行ログが確認できること）"],
            ['category' => 'Git/GitHub', 'order' => 5, 'level' => 5, 'title' => '本番グレードのCI/CDパイプラインを構築する', 'description' => "【課題内容】\nテスト・ビルド・デプロイ・通知を含む本番グレードのCI/CDパイプラインを構築する。\n\n【要件】\n・テスト → ビルド → ステージングデプロイ → 本番デプロイの段階的なパイプラインを実装すること\n・本番デプロイに手動承認ステップを追加すること\n・デプロイ後のヘルスチェックを実装すること\n・Slackまたはメールへの通知を設定すること\n\n【提出物】\n・GitHubリポジトリURL\n・CI/CDパイプラインの設計図・フロー図"],
            ['category' => 'Git/GitHub', 'order' => 6, 'level' => 5, 'title' => 'コードレビューを受ける', 'description' => "【課題内容】\nGitHubのプルリクエストを使いコードレビューを受け、フィードバックをもとに改善する。\n\n【要件】\n・機能追加のプルリクエストを作成すること\n・プルリクエストに変更内容・動作確認方法を記載すること\n・レビュアーからのコメントに対応すること\n・承認後にmainブランチにマージすること\n\n【提出物】\n・GitHubプルリクエストURL"],

            // Linux/Docker
            ['category' => 'Linux/Docker', 'order' => 1, 'level' => 1, 'title' => 'Linuxコマンドをマスターする', 'description' => "【課題内容】\n開発で頻繁に使うLinuxコマンドを習得し、操作記録をまとめる。\n\n【要件】\n・ファイル操作（ls・cd・mkdir・rm・cp・mv・cat・less）を習得すること\n・テキスト処理（grep・sed・awk・sort・uniq）を習得すること\n・プロセス管理（ps・kill・top）を習得すること\n・権限管理（chmod・chown・sudo）を習得すること\n・各コマンドの使い方と実行例をまとめたドキュメントを作成すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => 'Linux/Docker', 'order' => 2, 'level' => 1, 'title' => 'Dockerの基礎を理解する', 'description' => "【課題内容】\nDockerの基本概念を理解し、コンテナを操作する。\n\n【要件】\n・Dockerのイメージ・コンテナ・レジストリの概念をまとめること\n・docker pull・run・ps・stop・rm・imagesコマンドを使えること\n・Dockerfileを作成しカスタムイメージをビルドすること\n・nginxコンテナを起動しブラウザでアクセスできること\n\n【提出物】\n・GitHubリポジトリURL（Dockerfile含む）\n・まとめドキュメントのURL"],
            ['category' => 'Linux/Docker', 'order' => 3, 'level' => 2, 'title' => 'Docker Composeで複数コンテナを管理する', 'description' => "【課題内容】\nDocker Composeを使いWebサーバー・アプリ・DBの複数コンテナを管理する。\n\n【要件】\n・docker-compose.ymlにnginx・アプリ・DBの3コンテナを定義すること\n・docker compose upでコンテナが起動しブラウザでアクセスできること\n・コンテナ間のネットワーク設定を行うこと\n・データの永続化のためにボリュームを設定すること\n・環境変数を.envで管理すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Linux/Docker', 'order' => 4, 'level' => 2, 'title' => 'Nginxを設定する', 'description' => "【課題内容】\nNginxをリバースプロキシとして設定し、アプリへのリクエストを転送する。\n\n【要件】\n・NginxをDockerで起動すること\n・リバースプロキシとしてアプリサーバー（Laravel・Expressなど）にリクエストを転送すること\n・静的ファイル（HTML・CSS・JS・画像）をNginxから直接配信すること\n・gzip圧縮を設定すること\n・nginx.confの設定内容をREADMEで説明すること\n\n【提出物】\n・GitHubリポジトリURL"],
            ['category' => 'Linux/Docker', 'order' => 5, 'level' => 2, 'title' => 'VPSにLaravelを手動デプロイする', 'description' => "【課題内容】\nVPSにSSHで接続しLaravelアプリを手動デプロイする。\n\n【要件】\n・SSHでVPSに接続できること\n・Nginx・PHP・Composerをセットアップすること\n・GitHubからコードをクローンしcomposer installを実行すること\n・.envを設定しphp artisan migrateを実行すること\n・ブラウザからアプリにアクセスできること\n・デプロイ手順をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・デプロイ手順のREADME"],
            ['category' => 'Linux/Docker', 'order' => 6, 'level' => 3, 'title' => 'Dockerイメージを最適化する', 'description' => "【課題内容】\nマルチステージビルドとキャッシュ最適化でDockerイメージのサイズと速度を改善する。\n\n【要件】\n・マルチステージビルドを使いイメージサイズを削減すること\n・COPYの順序を最適化しキャッシュを活用すること\n・.dockerignoreを設定し不要ファイルを除外すること\n・最適化前後のイメージサイズとビルド時間を比較してREADMEに記載すること\n\n【提出物】\n・GitHubリポジトリURL\n・最適化レポートのREADME"],

            // AWS
            ['category' => 'AWS', 'order' => 1, 'level' => 2, 'title' => 'AWSの基礎サービスを理解する', 'description' => "【課題内容】\nAWSの主要サービスをまとめたドキュメントを作成する。\n\n【要件】\n・EC2・S3・RDS・VPC・IAM・CloudFrontの概要と使いどころを説明すること\n・リージョンとアベイラビリティゾーンの概念を説明すること\n・IAMのユーザー・グループ・ロール・ポリシーの違いを説明すること\n・AWSコンソールにログインし各サービスの画面を確認すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => 'AWS', 'order' => 2, 'level' => 2, 'title' => 'EC2にLaravelをデプロイする', 'description' => "【課題内容】\nEC2インスタンスを作成しLaravelアプリをデプロイする。\n\n【要件】\n・EC2インスタンス（Ubuntu）を起動しSSH接続できること\n・Nginx・PHP8.x・Composerをインストールすること\n・GitHubからコードをクローンし環境変数を設定すること\n・php artisan migrateを実行しLaravelが動作すること\n・セキュリティグループで80番・443番ポートのみ開放すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・デプロイ手順のREADME"],
            ['category' => 'AWS', 'order' => 3, 'level' => 2, 'title' => 'RDSでMySQLを本番運用する', 'description' => "【課題内容】\nRDSのMySQLインスタンスを作成しEC2のLaravelアプリから接続する。\n\n【要件】\n・RDS（MySQL 8.0）インスタンスを作成すること\n・EC2のセキュリティグループからのみRDSへのアクセスを許可すること\n・LaravelのDB設定をRDSのエンドポイントに変更すること\n・php artisan migrate:freshでテーブルを作成できること\n・RDSの自動バックアップを有効化すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'AWS', 'order' => 4, 'level' => 2, 'title' => 'S3で静的ファイルを管理する', 'description' => "【課題内容】\nS3バケットを作成しLaravelから画像をアップロード・配信できるようにする。\n\n【要件】\n・S3バケットを作成しLaravelのFilesystemにS3ドライバを設定すること\n・IAMロールを使いEC2からS3に安全にアクセスできること\n・画像のアップロード・取得・削除をLaravel経由で実装すること\n・CloudFront経由でS3の画像を配信できること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL"],
            ['category' => 'AWS', 'order' => 5, 'level' => 2, 'title' => 'HTTPS化とSSL証明書を設定する', 'description' => "【課題内容】\nWebサイトをHTTPS化しSSL証明書を設定する。\n\n【要件】\n・Let\'s Encryptを使いSSL証明書を取得しNginxに設定すること（またはACM+ALBを使用）\n・HTTPへのアクセスをHTTPSにリダイレクトすること\n・証明書の有効期限と自動更新の仕組みを確認すること\n・ブラウザで鍵マークが表示されることを確認すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL（https://）"],
            ['category' => 'AWS', 'order' => 6, 'level' => 2, 'title' => 'CloudWatchで監視・アラートを設定する', 'description' => "【課題内容】\nCloudWatchでEC2・RDSのリソースを監視しアラートを設定する。\n\n【要件】\n・EC2のCPU使用率・メモリ・ディスク使用率を監視すること\n・RDSのCPU・接続数・ストレージを監視すること\n・CPU使用率が80%を超えた場合にSNS経由でメール通知を設定すること\n・CloudWatchダッシュボードを作成すること\n\n【提出物】\n・CloudWatchダッシュボードのスクリーンショット\n・アラート設定のREADME"],
            ['category' => 'AWS', 'order' => 7, 'level' => 3, 'title' => 'Terraformでインフラをコード化する', 'description' => "【課題内容】\nTerraformを使いAWSインフラをコードで定義・管理する。\n\n【要件】\n・Terraformをインストールしaws providerを設定すること\n・VPC・サブネット・EC2・セキュリティグループをTerraformで定義すること\n・terraform plan・applyでリソースを作成できること\n・tfstateをS3バックエンドで管理すること\n・terraform destroyでリソースを削除できること\n\n【提出物】\n・GitHubリポジトリURL（.tfファイル含む）"],
            ['category' => 'AWS', 'order' => 8, 'level' => 3, 'title' => 'Ansibleでサーバー設定を自動化する', 'description' => "【課題内容】\nAnsibleのPlaybookを使いサーバーのセットアップを自動化する。\n\n【要件】\n・Ansibleをインストールしインベントリファイルを設定すること\n・Nginx・PHP・ComposerのインストールをPlaybookで自動化すること\n・Laravelアプリのデプロイ手順をPlaybookで自動化すること\n・ansible-playbookコマンドで全セットアップが完了すること\n\n【提出物】\n・GitHubリポジトリURL（Playbook含む）\n・実行手順のREADME"],
            ['category' => 'AWS', 'order' => 9, 'level' => 3, 'title' => 'ECSでコンテナをAWSで動かす', 'description' => "【課題内容】\nECS（Fargate）を使いDockerコンテナをAWS上で動かす。\n\n【要件】\n・ECRにDockerイメージをpushすること\n・ECSのタスク定義を作成しコンテナの設定を行うこと\n・ECSサービスを作成しコンテナを起動すること\n・ALBを設定しHTTP/HTTPSでアクセスできること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・ECS構成図"],
            ['category' => 'AWS', 'order' => 10, 'level' => 3, 'title' => 'Kubernetesの基礎を理解する', 'description' => "【課題内容】\nKubernetesの概念を学び、EKSまたはローカル（minikube）でコンテナを動かす。\n\n【要件】\n・Pod・Service・Deployment・Namespaceの概念をまとめること\n・Deploymentを使いコンテナのデプロイと更新を実装すること\n・Serviceを使いPodを外部に公開すること\n・kubectlコマンドの基本操作（apply・get・describe・delete）を習得すること\n\n【提出物】\n・GitHubリポジトリURL（yamlマニフェスト含む）\n・まとめドキュメントのURL"],
            ['category' => 'AWS', 'order' => 11, 'level' => 3, 'title' => 'DBバックアップと障害復旧を実装する', 'description' => "【課題内容】\nRDSのバックアップと障害復旧の手順を実践する。\n\n【要件】\n・RDSの自動バックアップを有効化し保持期間を設定すること\n・手動スナップショットを取得すること\n・スナップショットから新しいRDSインスタンスを復元できること\n・障害復旧計画（RTO・RPOを含む）をドキュメントにまとめること\n\n【提出物】\n・障害復旧計画ドキュメントのURL\n・復元手順のREADME"],
            ['category' => 'AWS', 'order' => 12, 'level' => 3, 'title' => 'コスト最適化をする', 'description' => "【課題内容】\nAWSのコストを分析し、最適化施策を実施する。\n\n【要件】\n・AWSコストエクスプローラーでサービス別のコストを分析すること\n・AWS Budgetsで月次予算アラートを設定すること\n・不要なリソースを特定し削除すること\n・コスト最適化の施策（スポットインスタンス・リザーブドインスタンス等）をまとめること\n\n【提出物】\n・コスト最適化レポートのドキュメントURL"],
            ['category' => 'AWS', 'order' => 13, 'level' => 4, 'title' => 'マルチAZ構成で高可用性を実現する', 'description' => "【課題内容】\nマルチAZ構成のインフラを構築し高可用性を実現する。\n\n【要件】\n・ALBと複数のEC2インスタンス（マルチAZ配置）で負荷分散を構成すること\n・RDSのマルチAZを有効化すること\n・Auto Scalingグループを設定しEC2を自動でスケールアウト/インできること\n・AZに障害が発生してもサービスが継続できることを確認すること\n\n【提出物】\n・アーキテクチャ構成図\n・GitHubリポジトリURL（Terraform等のコード）"],
            ['category' => 'AWS', 'order' => 14, 'level' => 4, 'title' => 'サービスメッシュを理解する', 'description' => "【課題内容】\nサービスメッシュの概念をまとめたドキュメントを作成し、基本的な設定を試す。\n\n【要件】\n・サービスメッシュの役割（トラフィック管理・可観測性・セキュリティ）を説明すること\n・AWS App MeshまたはIstioの基本設定を試すこと\n・サービス間の通信・トレーシング・サーキットブレーカーを説明すること\n・実際の設定手順をREADMEにまとめること\n\n【提出物】\n・まとめドキュメントのURL\n・GitHubリポジトリURL"],
            ['category' => 'AWS', 'order' => 15, 'level' => 4, 'title' => 'SREの基礎を実践する', 'description' => "【課題内容】\nSREの概念を学び、信頼性指標を設定してモニタリングを実装する。\n\n【要件】\n・SLI・SLO・エラーバジェットをアプリに対して定義すること\n・CloudWatchでSLIを計測するダッシュボードを作成すること\n・X-Rayを使い分散トレーシングを設定すること\n・SREの考え方をまとめたドキュメントを作成すること\n\n【提出物】\n・まとめドキュメントのURL\n・CloudWatchダッシュボードのスクリーンショット"],
            ['category' => 'AWS', 'order' => 16, 'level' => 4, 'title' => 'パフォーマンステストをする', 'description' => "【課題内容】\n負荷テストを実施しボトルネックを特定して改善する。\n\n【要件】\n・k6またはGatlingを使い負荷テストを実施すること\n・同時接続数・レスポンスタイム・エラー率を計測すること\n・ボトルネック（DB・アプリ・ネットワーク等）を特定すること\n・改善策を実施し再テストで効果を確認すること\n・テスト結果レポートを作成すること\n\n【提出物】\n・パフォーマンステストレポートのURL\n・GitHubリポジトリURL（テストスクリプト含む）"],
            ['category' => 'AWS', 'order' => 17, 'level' => 5, 'title' => '卒業制作：本番グレードのインフラを構築する', 'description' => "【課題内容】\nTerraform・ECS・RDS・ALB・CloudWatchを組み合わせた本番グレードのAWSインフラを構築しアプリをデプロイする。\n\n【要件】\n・VPC・パブリック/プライベートサブネット・セキュリティグループをTerraformで定義すること\n・ECS（Fargate）でアプリコンテナを動かすこと\n・RDS（マルチAZ）をデータベースとして使うこと\n・ALBでHTTPS化・ロードバランシングを設定すること\n・CloudWatchでモニタリング・アラートを設定すること\n・GitHub ActionsでCI/CDを構築すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・アーキテクチャ構成図"],

            // SQL/DB設計
            ['category' => 'SQL/DB設計', 'order' => 1, 'level' => 1, 'title' => 'SQLの基本操作をマスターする', 'description' => "【課題内容】\nMySQLを使いSQLの基本操作を習得し、操作記録をまとめる。\n\n【要件】\n・SELECT・WHERE・ORDER BY・LIMIT・GROUP BY・HAVINGを使うこと\n・INSERT・UPDATE・DELETEを実装すること\n・集計関数（COUNT・SUM・AVG・MAX・MIN）を使うこと\n・実行したSQLをSQLファイルにまとめてGitHubにpushすること\n\n【提出物】\n・GitHubリポジトリURL（SQLファイル含む）"],
            ['category' => 'SQL/DB設計', 'order' => 2, 'level' => 1, 'title' => 'テーブル設計の基礎を理解する（正規化）', 'description' => "【課題内容】\n正規化の概念を理解し、適切なテーブル設計を行う。\n\n【要件】\n・第1〜第3正規形の定義をまとめること\n・非正規形のテーブルを第3正規形まで正規化すること\n・ER図（エンティティ関連図）を作成すること（draw.io・Figma等）\n・正規化の前後でデータの重複がどう変化したかを説明すること\n\n【提出物】\n・まとめドキュメントのURL\n・ER図のURL"],
            ['category' => 'SQL/DB設計', 'order' => 3, 'level' => 2, 'title' => 'リレーションとJOINを使う', 'description' => "【課題内容】\n外部キーを使ったリレーションを設計し、JOINで複数テーブルを結合する。\n\n【要件】\n・外部キー制約を設定したテーブルを最低2つ作成すること\n・INNER JOIN・LEFT JOIN・RIGHT JOINを使ったクエリを実装すること\n・多対多のリレーションを中間テーブルで実装すること\n・サブクエリを使ったクエリを最低1つ実装すること\n\n【提出物】\n・GitHubリポジトリURL（SQLファイル含む）"],
            ['category' => 'SQL/DB設計', 'order' => 4, 'level' => 2, 'title' => 'インデックスでクエリを高速化する', 'description' => "【課題内容】\nインデックスを適切に設定し、クエリを高速化する。\n\n【要件】\n・EXPLAINでクエリの実行計画を確認すること\n・インデックスがない状態とある状態のクエリ実行時間を比較すること\n・複合インデックスを設定し効果を確認すること\n・インデックスを設定すべきでないケースについてまとめること\n\n【提出物】\n・まとめドキュメントのURL\n・GitHubリポジトリURL（SQLファイル含む）"],
            ['category' => 'SQL/DB設計', 'order' => 5, 'level' => 3, 'title' => 'トランザクションとロックを理解する', 'description' => "【課題内容】\nトランザクションとロックの仕組みを理解し、整合性を保つSQL設計を行う。\n\n【要件】\n・BEGIN・COMMIT・ROLLBACKを使いトランザクションを実装すること\n・デッドロックを意図的に発生させ、解消方法を説明すること\n・SELECT ... FOR UPDATE（悲観ロック）を実装すること\n・楽観ロック（バージョンカラム）を実装すること\n\n【提出物】\n・まとめドキュメントのURL\n・GitHubリポジトリURL"],
            ['category' => 'SQL/DB設計', 'order' => 6, 'level' => 3, 'title' => 'ストアドプロシージャを作る', 'description' => "【課題内容】\nMySQLのストアドプロシージャを作成し、複雑な処理をDB側で実装する。\n\n【要件】\n・引数と戻り値を持つストアドプロシージャを最低2つ作成すること\n・ストアドプロシージャ内で条件分岐・ループを使うこと\n・エラーハンドリング（DECLARE HANDLER）を実装すること\n・作成したプロシージャの使い方をREADMEで説明すること\n\n【提出物】\n・GitHubリポジトリURL（SQLファイル含む）"],
            ['category' => 'SQL/DB設計', 'order' => 7, 'level' => 4, 'title' => 'DB設計パターンを学ぶ', 'description' => "【課題内容】\n実践的なDB設計パターンを学びユースケースに応じた設計を行う。\n\n【要件】\n・ポリモーフィック関連の設計とSQLを実装すること\n・ツリー構造（隣接リスト・経路列挙・入れ子集合のいずれか）を実装すること\n・ソフトデリート（deleted_atカラム）を実装すること\n・各パターンの使いどころをまとめたドキュメントを作成すること\n\n【提出物】\n・まとめドキュメントのURL\n・GitHubリポジトリURL"],
            ['category' => 'SQL/DB設計', 'order' => 8, 'level' => 4, 'title' => 'パフォーマンスチューニングをする', 'description' => "【課題内容】\nDBのパフォーマンスを計測し、改善施策を実施する。\n\n【要件】\n・スロークエリログを有効化し遅いクエリを特定すること\n・EXPLAINでクエリの問題点（FULLSCan・temporaryなど）を分析すること\n・インデックスの追加またはクエリの書き換えで改善すること\n・改善前後のクエリ実行時間を比較しレポートを作成すること\n\n【提出物】\n・パフォーマンスチューニングレポートのURL"],

            // UI/UXデザイン
            ['category' => 'UI/UXデザイン', 'order' => 1, 'level' => 1, 'title' => 'UIとUXの違いを理解する', 'description' => "【課題内容】\nUIとUXの違いと良いデザインの原則をまとめたドキュメントを作成する。\n\n【要件】\n・UIとUXの定義と違いを説明すること\n・ユーザー中心設計（UCD）の考え方を説明すること\n・良いUX・悪いUXの具体的な例を3つ以上挙げること\n・Webサービスを1つ選び、UIとUXの観点から評価すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => 'UI/UXデザイン', 'order' => 2, 'level' => 1, 'title' => 'Figmaの基本操作をマスターする', 'description' => "【課題内容】\nFigmaの基本操作を習得し、簡単な画面デザインを作成する。\n\n【要件】\n・フレーム・テキスト・シェイプ・画像の配置操作を習得すること\n・カラー・フォント・シャドウを設定すること\n・コンポーネント（ボタン・カード）を最低2つ作成すること\n・作成した画面をFigmaの共有リンクで公開すること\n\n【提出物】\n・FigmaデザインURL"],
            ['category' => 'UI/UXデザイン', 'order' => 3, 'level' => 2, 'title' => 'コンポーネント設計でデザインを効率化する', 'description' => "【課題内容】\nFigmaのコンポーネントを使い、再利用可能なUIデザインシステムを構築する。\n\n【要件】\n・コンポーネント（ボタン・インプット・カード・ナビゲーション）を最低5種類作成すること\n・バリアントを使いコンポーネントのstate（デフォルト・ホバー・無効化）を管理すること\n・Auto Layoutを使いコンポーネントが自動でリサイズされるようにすること\n・デザインシステムのカラー・タイポグラフィをスタイルで定義すること\n\n【提出物】\n・FigmaデザインURL"],
            ['category' => 'UI/UXデザイン', 'order' => 4, 'level' => 2, 'title' => 'カラー・タイポグラフィの基礎を学ぶ', 'description' => "【課題内容】\nカラーとタイポグラフィの基礎を学び、デザインに適用する。\n\n【要件】\n・補色・類似色・3色配色などの配色理論を説明すること\n・コントラスト比がWCAGのAA基準（4.5:1以上）を満たすカラーパレットを作成すること\n・フォントの種類（セリフ・サンセリフ・モノスペース）の特徴と使い分けを説明すること\n・タイポグラフィスケール（見出し・本文・キャプション）を定義したFigmaデザインを作成すること\n\n【提出物】\n・FigmaデザインURL\n・まとめドキュメントのURL"],
            ['category' => 'UI/UXデザイン', 'order' => 5, 'level' => 2, 'title' => 'ワイヤーフレームを作る', 'description' => "【課題内容】\nWebアプリの画面構成をFigmaでワイヤーフレームとして設計する。\n\n【要件】\n・最低5画面のワイヤーフレームを作成すること\n・各画面のUI要素（ヘッダー・ナビ・コンテンツ・フッター）を配置すること\n・PCとスマートフォンの2つのレイアウトを設計すること\n・各画面の目的・ユーザーの操作フローをドキュメントで説明すること\n\n【提出物】\n・FigmaデザインURL\n・画面設計ドキュメントのURL"],
            ['category' => 'UI/UXデザイン', 'order' => 6, 'level' => 3, 'title' => 'プロトタイプを作る', 'description' => "【課題内容】\nFigmaのプロトタイプ機能を使い、操作できるインタラクティブなデモを作成する。\n\n【要件】\n・画面間のトランジション（スライド・フェードなど）を設定すること\n・ボタンのホバー・クリック状態のインタラクションを設定すること\n・フォームの入力→送信→完了画面の一連の流れを実装すること\n・Figmaの共有リンクでプロトタイプを操作できる状態にすること\n\n【提出物】\n・FigmaプロトタイプURL"],
            ['category' => 'UI/UXデザイン', 'order' => 7, 'level' => 3, 'title' => 'デザインカンプをコーディングする', 'description' => "【課題内容】\nFigmaで作成したデザインカンプをHTML/CSS/Reactでコーディングして実装する。\n\n【要件】\n・FigmaのデザインをHTML/CSSまたはReactで再現すること\n・余白・フォントサイズ・色をデザインカンプに合わせること\n・レスポンシブ対応（スマートフォン・PC）を実装すること\n・デザインとの差異が最小になるよう実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・FigmaデザインURL"],
            ['category' => 'UI/UXデザイン', 'order' => 8, 'level' => 4, 'title' => 'アクセシビリティを考慮したデザインをする', 'description' => "【課題内容】\nWCAG 2.1に準拠したアクセシブルなデザインと実装を行う。\n\n【要件】\n・カラーコントラスト比が4.5:1以上になっていることを確認すること\n・フォームにlabelとaria-labelを適切に設定すること\n・キーボードのTabキーのみで全コンテンツにアクセスできること\n・スクリーンリーダー（NVDA・VoiceOver等）で内容が読み上げられることを確認すること\n・LighthouseでアクセシビリティスコアがA以上になること\n\n【提出物】\n・GitHubリポジトリURL\n・デプロイURL\n・アクセシビリティ対応レポートのURL"],

            // セキュリティ
            ['category' => 'セキュリティ', 'order' => 1, 'level' => 1, 'title' => 'セキュリティの基本概念を理解する', 'description' => "【課題内容】\n情報セキュリティの基本概念をまとめたドキュメントを作成する。\n\n【要件】\n・情報セキュリティのCIA（機密性・完全性・可用性）を説明すること\n・認証・認可・監査の違いを説明すること\n・Webアプリケーションに存在する主な脅威（OWASP Top10から最低5つ）を説明すること\n・セキュリティを高めるための基本的な対策をまとめること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 2, 'level' => 1, 'title' => 'OWASP Top10を学ぶ', 'description' => "【課題内容】\nOWASP Top10の脆弱性を調査し、各脆弱性の対策をまとめたドキュメントを作成する。\n\n【要件】\n・OWASP Top10の全項目の概要を説明すること\n・各脆弱性の攻撃の仕組みと具体的な被害例を説明すること\n・各脆弱性に対する具体的な対策を説明すること\n・実際のセキュリティ事故（公開情報のみ）を1件取り上げ分析すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 3, 'level' => 2, 'title' => 'SQLインジェクション対策を実装する', 'description' => "【課題内容】\nSQLインジェクションの仕組みを理解し、対策を実装する。\n\n【要件】\n・SQLインジェクションが発生する脆弱なコードを書き、攻撃を再現すること（ローカル環境のみ）\n・プリペアドステートメントを使い対策を実装すること\n・ORMを使い対策を実装すること\n・入力値のサニタイズとバリデーションを実装すること\n・脆弱なコードと安全なコードの比較をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 4, 'level' => 2, 'title' => 'XSS対策を実装する', 'description' => "【課題内容】\nクロスサイトスクリプティング（XSS）の仕組みを理解し、対策を実装する。\n\n【要件】\n・XSSが発生する脆弱なコードを書き、攻撃を再現すること（ローカル環境のみ）\n・出力エスケープを使い対策を実装すること\n・Content Security Policy（CSP）ヘッダーを設定すること\n・HttpOnly・SameSite CookieフラグでCookie保護を設定すること\n・脆弱なコードと安全なコードの比較をREADMEにまとめること\n\n【提出物】\n・GitHubリポジトリURL\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 5, 'level' => 2, 'title' => 'CSRF対策を実装する', 'description' => "【課題内容】\nCSRF攻撃の仕組みを理解し、対策を実装する。\n\n【要件】\n・CSRF攻撃の仕組みをまとめること\n・CSRFトークンを使った対策を実装すること\n・SameSite Cookieを設定すること\n・LaravelのCSRF保護の仕組みを説明すること\n・Refererヘッダーによる検証の限界についても説明すること\n\n【提出物】\n・GitHubリポジトリURL\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 6, 'level' => 3, 'title' => '認証・認可のベストプラクティスを学ぶ', 'description' => "【課題内容】\n認証・認可のベストプラクティスをまとめ、安全な認証機能を実装する。\n\n【要件】\n・パスワードをbcryptでハッシュ化して保存すること\n・JWTの安全な発行・検証・無効化の仕組みを説明すること\n・レートリミット（ログイン試行回数制限）を実装すること\n・多要素認証（MFA）の仕組みを説明すること\n・アカウントロックアウトの仕組みを実装すること\n\n【提出物】\n・GitHubリポジトリURL\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 7, 'level' => 3, 'title' => '暗号化の基礎を理解する', 'description' => "【課題内容】\n暗号化の仕組みをまとめたドキュメントを作成する。\n\n【要件】\n・共通鍵暗号と公開鍵暗号の違いを説明すること\n・ハッシュ関数の特性（一方向性・衝突耐性）を説明すること\n・TLS/HTTPSの通信の仕組みをハンドシェイクから説明すること\n・デジタル署名の仕組みを説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => 'セキュリティ', 'order' => 8, 'level' => 4, 'title' => 'セキュリティ診断を実施する', 'description' => "【課題内容】\n自作のWebアプリに対してセキュリティ診断を実施し、脆弱性を修正する。\n\n【要件】\n・OWASP ZAP（またはBurp Suite）を使い自作アプリのスキャンを実施すること\n・発見された脆弱性を一覧化しリスク評価を行うこと\n・高リスクの脆弱性を修正すること\n・診断前後の結果を比較したレポートを作成すること\n\n【提出物】\n・GitHubリポジトリURL\n・セキュリティ診断レポートのURL"],

            // 基本情報技術者試験
            ['category' => '基本情報技術者試験', 'order' => 1, 'level' => 1, 'title' => 'コンピュータの基礎を理解する（2進数・論理回路）', 'description' => "【課題内容】\n基本情報技術者試験のコンピュータの基礎分野を学習しまとめる。\n\n【要件】\n・2進数・8進数・16進数の相互変換を説明すること\n・AND・OR・NOT・NAND・XOR論理演算を説明すること\n・補数表現（2の補数）を使った負の数の表現を説明すること\n・フリップフロップ・レジスタ・メモリの仕組みを説明すること\n・各単元の確認問題（過去問から抜粋）を解いて正答率を記録すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 2, 'level' => 1, 'title' => 'データ構造とアルゴリズムを学ぶ', 'description' => "【課題内容】\n基本情報技術者試験のアルゴリズム分野を学習しまとめる。\n\n【要件】\n・配列・スタック・キュー・連結リスト・木構造の仕組みを説明すること\n・バブルソート・選択ソート・クイックソートを実装し計算量を比較すること\n・2分探索アルゴリズムを実装すること\n・再帰アルゴリズムの例（フィボナッチ数列・階乗計算）を実装すること\n\n【提出物】\n・GitHubリポジトリURL（実装コード含む）\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 3, 'level' => 2, 'title' => 'OSの基礎を理解する', 'description' => "【課題内容】\nOSの基本機能をまとめたドキュメントを作成する。\n\n【要件】\n・プロセス管理（プロセス・スレッド・スケジューリング）を説明すること\n・メモリ管理（ページング・セグメント・仮想メモリ）を説明すること\n・ファイルシステムの仕組みを説明すること\n・デッドロックの発生条件と回避策を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 4, 'level' => 2, 'title' => 'ネットワークの基礎を理解する', 'description' => "【課題内容】\nネットワークの基礎をまとめたドキュメントを作成する。\n\n【要件】\n・OSI参照モデルの7層とTCP/IPの4層を説明すること\n・IPアドレス・サブネットマスク・デフォルトゲートウェイを説明すること\n・DNSの名前解決の仕組みを説明すること\n・HTTPとHTTPSの違い、SSL/TLSの仕組みを説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 5, 'level' => 2, 'title' => 'セキュリティの基礎を理解する', 'description' => "【課題内容】\n情報セキュリティの基礎をまとめたドキュメントを作成する。\n\n【要件】\n・暗号化（共通鍵・公開鍵）とデジタル署名を説明すること\n・認証技術（パスワード・多要素認証・生体認証）を説明すること\n・ファイアウォール・IDS・IPSの役割を説明すること\n・マルウェアの種類（ウイルス・ランサムウェア・トロイの木馬等）を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 6, 'level' => 2, 'title' => 'データベースの基礎を理解する', 'description' => "【課題内容】\nデータベースの基礎をまとめたドキュメントを作成する。\n\n【要件】\n・リレーショナルデータベースの概念と正規化を説明すること\n・SQL（SELECT・INSERT・UPDATE・DELETE・JOIN）の基本を説明すること\n・トランザクションとACID特性を説明すること\n・インデックスの仕組みと効果を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 7, 'level' => 3, 'title' => 'ソフトウェア開発手法を学ぶ', 'description' => "【課題内容】\nソフトウェア開発手法をまとめたドキュメントを作成する。\n\n【要件】\n・ウォーターフォール・アジャイル・スクラムの特徴と違いを説明すること\n・テスト手法（単体・結合・システム・受入テスト）を説明すること\n・品質管理（QA・デバッグ・ホワイトボックス/ブラックボックステスト）を説明すること\n・プロジェクト管理（WBS・ガントチャート・クリティカルパス）を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '基本情報技術者試験', 'order' => 8, 'level' => 3, 'title' => '過去問演習をする', 'description' => "【課題内容】\n基本情報技術者試験の過去問を演習し、弱点を特定して学習する。\n\n【要件】\n・科目A（旧午前）の過去問を100問以上解くこと\n・科目B（旧午後）のアルゴリズム問題を10問以上解くこと\n・各分野のスコアを記録し弱点分野を特定すること\n・弱点分野を重点的に学習し再度過去問を解いて改善を確認すること\n・演習記録と得点推移をまとめたドキュメントを作成すること\n\n【提出物】\n・演習記録ドキュメントのURL"],

            // 応用情報技術者試験
            ['category' => '応用情報技術者試験', 'order' => 1, 'level' => 2, 'title' => 'アルゴリズムと計算量を理解する', 'description' => "【課題内容】\n応用情報技術者試験レベルのアルゴリズムと計算量を学習しまとめる。\n\n【要件】\n・O記法（ビッグオー記法）の概念を説明すること\n・主要なソートアルゴリズムの計算量を比較すること\n・動的計画法の概念と例題（ナップサック問題等）を説明すること\n・再帰アルゴリズムとメモ化の最適化を実装すること\n\n【提出物】\n・まとめドキュメントのURL\n・GitHubリポジトリURL（実装コード含む）"],
            ['category' => '応用情報技術者試験', 'order' => 2, 'level' => 2, 'title' => 'システムアーキテクチャを学ぶ', 'description' => "【課題内容】\nシステムアーキテクチャの概念をまとめたドキュメントを作成する。\n\n【要件】\n・クライアントサーバー・3層・N層アーキテクチャを説明すること\n・SoA（サービス指向アーキテクチャ）とマイクロサービスを説明すること\n・可用性の指標（稼働率・MTBF・MTTR）を計算式とともに説明すること\n・冗長化（ホットスタンバイ・ウォームスタンバイ・コールドスタンバイ）を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '応用情報技術者試験', 'order' => 3, 'level' => 2, 'title' => 'ネットワーク技術を深く理解する', 'description' => "【課題内容】\n応用情報レベルのネットワーク技術をまとめたドキュメントを作成する。\n\n【要件】\n・ルーティングプロトコル（OSPF・BGP）を説明すること\n・VLAN・VPN（IPsec・SSL-VPN）を説明すること\n・ロードバランサー（L4・L7）の違いと動作を説明すること\n・CDNの仕組みと効果を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '応用情報技術者試験', 'order' => 4, 'level' => 3, 'title' => 'データベース応用を学ぶ', 'description' => "【課題内容】\n応用情報レベルのデータベース技術をまとめたドキュメントを作成する。\n\n【要件】\n・障害回復（ロールフォワード・ロールバック・チェックポイント）を説明すること\n・同時実行制御（直列化可能性・2相ロック）を説明すること\n・分散データベースのCAP定理を説明すること\n・NoSQL（KVS・ドキュメント・グラフDB）の特徴と使い分けを説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '応用情報技術者試験', 'order' => 5, 'level' => 3, 'title' => 'セキュリティ技術を深く学ぶ', 'description' => "【課題内容】\n応用情報レベルのセキュリティ技術をまとめたドキュメントを作成する。\n\n【要件】\n・PKI（公開鍵基盤）・認証局・デジタル証明書の仕組みを説明すること\n・S/MIME・TLS・IPsecのプロトコルを説明すること\n・インシデント対応の手順（検知→封じ込め→復旧→再発防止）を説明すること\n・ペネトレーションテストとセキュリティ診断の違いを説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '応用情報技術者試験', 'order' => 6, 'level' => 3, 'title' => 'プロジェクトマネジメントを学ぶ', 'description' => "【課題内容】\n応用情報のプロジェクトマネジメント分野をまとめたドキュメントを作成する。\n\n【要件】\n・WBS（作業分解構造）の作成方法を説明すること\n・クリティカルパス法（CPM）の計算方法を例題で説明すること\n・リスク管理（識別・分析・対応計画）のプロセスを説明すること\n・EVM（アーンドバリュー管理）の指標（SV・CV・SPI・CPI）を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '応用情報技術者試験', 'order' => 7, 'level' => 4, 'title' => 'システム開発技術を学ぶ', 'description' => "【課題内容】\n応用情報のシステム開発技術分野をまとめたドキュメントを作成する。\n\n【要件】\n・オブジェクト指向設計のSOLID原則を説明すること\n・UMLの主要図（クラス図・シーケンス図・ユースケース図）を説明すること\n・代表的なデザインパターン（Singleton・Observer・Factoryなど）を3つ以上説明すること\n・ソフトウェアテスト技法（同値分割・境界値分析・デシジョンテーブル）を説明すること\n\n【提出物】\n・まとめドキュメントのURL"],
            ['category' => '応用情報技術者試験', 'order' => 8, 'level' => 4, 'title' => '過去問演習をする（応用）', 'description' => "【課題内容】\n応用情報技術者試験の過去問を演習し、合格レベルの実力をつける。\n\n【要件】\n・午前問題の過去問を100問以上解くこと\n・午後問題（記述式）を5回分以上解くこと\n・午後問題の必須選択（情報セキュリティ・プログラミング）の解答力を重点強化すること\n・各分野の得点を記録し弱点分野を特定して集中学習すること\n・演習記録と得点推移をまとめたドキュメントを作成すること\n\n【提出物】\n・演習記録ドキュメントのURL"],
        ];

        foreach ($taskData as $task) {
            TaskMaster::create([
                'category'        => $task['category'],
                'order'           => $task['order'],
                'level'           => $task['level'],
                'title'           => $task['title'],
                'description'     => $task['description'],
                'is_official'     => true,
                'visibility'      => 'official',
                'organization_id' => null,
                'created_by'      => null,
            ]);
        }

        // パックデータ
        $packData = [
            ['name' => 'フロントエンド入門', 'description' => 'HTML/CSSからJavaScriptまでのWeb入門コース', 'tasks' => ['Webの仕組みを理解する', 'HTMLで自己紹介ページを作る', 'CSSでページをデザインする', 'Flexboxでナビゲーションバーを作る', 'CSS Gridでポートフォリオギャラリーを作る', 'JavaScriptで電卓を作る', '配列とループでクイズアプリを作る', 'LocalStorageでTodoアプリを作る', '非同期処理とPromiseを理解する']],
            ['name' => 'サーバーサイド入門', 'description' => 'PHP基礎からLaravel認証までの入門コース', 'tasks' => ['コマンドラインの基本操作をマスターする', 'PHPの基礎文法を習得する', 'PHPでオブジェクト指向を理解する', 'MySQLの基本操作をマスターする', 'PHPとMySQLを連携させる', 'LaravelとDockerで開発環境を構築する', 'MVC構造とルーティングを理解する', 'MigrationとEloquentでDB操作をする', 'Sanctumで認証APIを実装する']],
            ['name' => 'インフラ入門', 'description' => 'LinuxからGitHub Actionsまでの入門コース', 'tasks' => ['Linuxコマンドをマスターする', 'Dockerの基礎を理解する', 'Docker Composeで複数コンテナを管理する', 'Git/GitHubでバージョン管理をする', 'Git/GitHubでチーム開発の流れを理解する', 'VPSにLaravelを手動デプロイする']],
            ['name' => 'HTML/CSS', 'description' => 'HTMLとCSSの基礎からSCSSまで', 'tasks' => ['Webの仕組みを理解する', 'HTMLで自己紹介ページを作る', 'CSSでページをデザインする', 'Flexboxでナビゲーションバーを作る', 'CSS Gridでポートフォリオギャラリーを作る', 'SCSSでデザインシステムを作る']],
            ['name' => 'JavaScript基礎', 'description' => 'JavaScriptの基礎から非同期処理まで', 'tasks' => ['JavaScriptで電卓を作る', '配列とループでクイズアプリを作る', 'LocalStorageでTodoアプリを作る', 'Fetch APIで天気アプリを作る', '非同期処理とPromiseを理解する', 'モジュール分割でコードを整理する']],
            ['name' => 'React基礎', 'description' => 'Reactの基礎からAPI接続まで', 'tasks' => ['Reactでカウンターアプリを作る', 'useEffectでデータ取得アプリを作る', 'React Routerでマルチページアプリを作る', 'フォームバリデーションを実装する', 'Context APIでグローバル状態管理をする', 'axiosでLaravel APIに接続する']],
            ['name' => 'React応用', 'description' => 'カスタムフックからテストまで', 'tasks' => ['カスタムフックでロジックを分離する', 'ReactでドラッグandドロップUIを作る', 'テストコードを書く']],
            ['name' => 'TypeScript', 'description' => '型入門からReact×TypeScriptまで', 'tasks' => ['TypeScriptの基礎を理解する（型・インターフェース）', '関数と型注釈を使う', 'ジェネリクスを理解する', 'Reactコンポーネントを型付けする', 'APIレスポンスを型定義する', 'ユーティリティ型を使う', '既存JSプロジェクトをTSに移行する']],
            ['name' => 'PHP基礎', 'description' => 'PHPの文法からMySQL連携まで', 'tasks' => ['PHPの基礎文法を習得する', 'PHPでオブジェクト指向を理解する', 'MySQLの基本操作をマスターする', 'PHPとMySQLを連携させる']],
            ['name' => 'Laravel基礎', 'description' => '環境構築からSanctum認証まで', 'tasks' => ['LaravelとDockerで開発環境を構築する', 'MVC構造とルーティングを理解する', 'MigrationとEloquentでDB操作をする', 'リレーションとeager loadingを使う', 'バリデーションとエラーレスポンスを実装する', 'Sanctumで認証APIを実装する', 'APIリソースでレスポンスを整形する']],
            ['name' => 'Laravel応用', 'description' => 'ファイルアップロードからテストまで', 'tasks' => ['ファイルアップロードを実装する', '検索・フィルタ・ソートAPIを作る', 'Policyで権限管理を実装する', 'キューとジョブで非同期処理をする', 'キャッシュでAPIを高速化する', 'DBトランザクションで整合性を保つ', 'PHPUnitでFeatureテストを書く']],
            ['name' => 'Python基礎', 'description' => 'Python環境構築からデータ処理まで', 'tasks' => ['Python環境構築をする', 'Pythonの基礎文法を習得する', 'リスト・辞書・タプルを使う', 'クラスとオブジェクト指向を理解する', 'ファイル操作をする', '外部ライブラリを使う（requests等）', 'データ処理をする（pandas入門）']],
            ['name' => 'Django', 'description' => 'Django入門からREST APIまで', 'tasks' => ['Djangoで開発環境を構築する', 'MVTパターンを理解する', 'モデルとマイグレーションを使う', 'ビューとテンプレートを作る', 'Formバリデーションを実装する', 'Django REST Frameworkを使う', '認証機能を実装する']],
            ['name' => 'Java基礎', 'description' => 'Java環境構築からJUnitまで', 'tasks' => ['Java環境構築をする', 'Javaの基礎文法を習得する', 'オブジェクト指向を理解する（クラス・継承）', '例外処理を実装する', 'コレクションを使う', 'ファイルI/Oを実装する', 'ユニットテストを書く（JUnit）']],
            ['name' => 'Spring Boot', 'description' => 'Spring Boot入門からセキュリティまで', 'tasks' => ['Spring Bootで開発環境を構築する', 'REST APIを作る', 'Spring Data JPAでDB操作をする', 'バリデーションを実装する', 'Spring Securityで認証を実装する', 'テストを書く']],
            ['name' => 'Git/GitHub基礎', 'description' => 'バージョン管理とチーム開発の基礎', 'tasks' => ['Git/GitHubでバージョン管理をする', 'Git/GitHubでチーム開発の流れを理解する']],
            ['name' => 'チーム開発', 'description' => 'コードレビューとCI/CDを含むチーム開発実践', 'tasks' => ['Git/GitHubでチーム開発の流れを理解する', 'GitHub ActionsでCIパイプラインを作る', 'GitHub ActionsでCDパイプラインを作る', 'コードレビューを受ける']],
            ['name' => 'Linux/Docker基礎', 'description' => 'LinuxとDockerの基礎', 'tasks' => ['Linuxコマンドをマスターする', 'Dockerの基礎を理解する', 'Docker Composeで複数コンテナを管理する', 'Dockerイメージを最適化する']],
            ['name' => 'CI/CD', 'description' => 'GitHub ActionsでCI/CDパイプラインを構築する', 'tasks' => ['GitHub ActionsでCIパイプラインを作る', 'GitHub ActionsでCDパイプラインを作る', '本番グレードのCI/CDパイプラインを構築する']],
            ['name' => 'AWS基礎', 'description' => 'AWSの基礎サービスからデプロイまで', 'tasks' => ['AWSの基礎サービスを理解する', 'EC2にLaravelをデプロイする', 'RDSでMySQLを本番運用する', 'S3で静的ファイルを管理する', 'HTTPS化とSSL証明書を設定する', 'CloudWatchで監視・アラートを設定する']],
            ['name' => 'AWS応用', 'description' => 'TerraformからECS・Kubernetesまで', 'tasks' => ['Terraformでインフラをコード化する', 'ECSでコンテナをAWSで動かす', 'Kubernetesの基礎を理解する', 'マルチAZ構成で高可用性を実現する']],
            ['name' => 'SQL/DB設計', 'description' => 'SQL基礎からDB設計パターンまで', 'tasks' => ['SQLの基本操作をマスターする', 'テーブル設計の基礎を理解する（正規化）', 'リレーションとJOINを使う', 'インデックスでクエリを高速化する', 'トランザクションとロックを理解する', 'DB設計パターンを学ぶ', 'パフォーマンスチューニングをする']],
            ['name' => 'UI/UXデザイン基礎', 'description' => 'FigmaからデザインカンプのコーディングまでUI/UX入門', 'tasks' => ['UIとUXの違いを理解する', 'Figmaの基本操作をマスターする', 'コンポーネント設計でデザインを効率化する', 'カラー・タイポグラフィの基礎を学ぶ', 'ワイヤーフレームを作る', 'プロトタイプを作る', 'デザインカンプをコーディングする', 'アクセシビリティを考慮したデザインをする']],
            ['name' => 'セキュリティ基礎', 'description' => 'OWASP・XSS・SQLインジェクションなどWebセキュリティの基礎', 'tasks' => ['セキュリティの基本概念を理解する', 'OWASP Top10を学ぶ', 'SQLインジェクション対策を実装する', 'XSS対策を実装する', 'CSRF対策を実装する', '認証・認可のベストプラクティスを学ぶ', '暗号化の基礎を理解する', 'セキュリティ診断を実施する']],
            ['name' => '基本情報技術者試験対策', 'description' => '基本情報技術者試験の出題範囲を体系的に学ぶ', 'tasks' => ['コンピュータの基礎を理解する（2進数・論理回路）', 'データ構造とアルゴリズムを学ぶ', 'OSの基礎を理解する', 'ネットワークの基礎を理解する', 'セキュリティの基礎を理解する', 'データベースの基礎を理解する', 'ソフトウェア開発手法を学ぶ', '過去問演習をする']],
            ['name' => '応用情報技術者試験対策', 'description' => '応用情報技術者試験の出題範囲を体系的に学ぶ', 'tasks' => ['アルゴリズムと計算量を理解する', 'システムアーキテクチャを学ぶ', 'ネットワーク技術を深く理解する', 'データベース応用を学ぶ', 'セキュリティ技術を深く学ぶ', 'プロジェクトマネジメントを学ぶ', 'システム開発技術を学ぶ', '過去問演習をする（応用）']],
        ];

        foreach ($packData as $pack) {
            $created = TaskPack::create([
                'organization_id' => null,
                'created_by'      => null,
                'name'            => $pack['name'],
                'description'     => $pack['description'],
                'is_official'     => true,
                'is_public'       => true,
            ]);

            foreach ($pack['tasks'] as $order => $title) {
                $task = TaskMaster::where('title', $title)->first();
                if ($task) {
                    TaskPackItem::create([
                        'task_pack_id'   => $created->id,
                        'task_master_id' => $task->id,
                        'order'          => $order + 1,
                    ]);
                }
            }
        }
    }
}
